// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Models;

namespace PetShop.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20200708230630_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetShop.Models.Junction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProduktID");

                    b.Property<int>("SopstvenikID");

                    b.HasKey("Id");

                    b.HasIndex("ProduktID");

                    b.HasIndex("SopstvenikID");

                    b.ToTable("Junction");
                });

            modelBuilder.Entity("PetShop.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NamenetoZa")
                        .IsRequired();

                    b.Property<string>("ProfilePicture");

                    b.HasKey("Id");

                    b.ToTable("Produkt");
                });

            modelBuilder.Entity("PetShop.Models.Sopstvenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Grad");

                    b.Property<string>("ImeMilenik")
                        .IsRequired();

                    b.Property<string>("ImePrezime")
                        .IsRequired();

                    b.Property<string>("ProfilePicture");

                    b.HasKey("Id");

                    b.ToTable("Sopstvenik");
                });

            modelBuilder.Entity("PetShop.Models.Junction", b =>
                {
                    b.HasOne("PetShop.Models.Produkt", "Produkt")
                        .WithMany("Sopstvenici")
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetShop.Models.Sopstvenik", "Sopstvenik")
                        .WithMany("Produkti")
                        .HasForeignKey("SopstvenikID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
